# -*- coding: utf-8 -*-
"""DVA_AIM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NB_RAcac-Vg7h6tJ6Nq2LS4zG0OJhTsm
"""

from google.colab import files
files.upload()

import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv("Company Sales Data.csv")
data

x=data["total_profit"]
y=data["month_number"]
plt.xlabel("Month")
plt.ylabel("Profit")
plt.title("RECORDS")
plt.plot(y,x, color = 'red',
         linestyle = 'dotted', marker = 'o',
         markerfacecolor = 'red', markersize = 12)

a=data["facecream"]
b=data["facewash"]
c=data["toothpaste"]
d=data["bathingsoap"]
e=data["shampoo"]
f=data["moisturizer"]
plt.plot(y,a,y,b,y,c,y,d,y,e,y,f)
plt.show()

plt.scatter(y,c,color="red")
plt.show()

plt.bar(y,b,color="green")
plt.show()

plt.bar(y,d,color="red")
plt.show()
plt.savefig('soap.png')

plt.hist(x,color="orange")
plt.title("Total profit")
plt.show()

a1=data["facecream"].sum()
b1=data["facewash"].sum()
c1=data["toothpaste"].sum()
d1=data["bathingsoap"].sum()
e1=data["shampoo"].sum()
f1=data["moisturizer"].sum()
print(a1,b1,c1,d1,e1,f1)

"""Subplot"""

x = d=data["bathingsoap"]
y = data["month_number"]

plt.subplot(1, 2, 1)
plt.plot(x,y)


x =data["bathingsoap"]
y = data["month_number"]

plt.subplot(1, 2, 2)
plt.plot(x,y)

plt.show()

"""Stackplot"""

plt.stackplot(y,a,b,c,d,e,f)
plt.show()

plt.boxplot(a)
plt.show()

"""IRIS DATASET"""

from google.colab import files
files.upload()

data_1=pd.read_csv("Iris_nonull.csv")
data_1

plt.barh(data_1["Species"],data_1["SepalLengthCm"])
plt.show()

print(data_1.corr())
import seaborn as sb

heatmap=sb.heatmap(data_1.corr(),annot=True)

"""Load the necessary package for plotting using pyplot from matplotlib. Example -
Days(x-axis) represents 8 days and Speed represents a car’s speed. Plot a Basic line
plot between days and car speed, put x axis label as days and y axis label as car
speed and put title Car Speed Measurement.
         Days=[1,2,3,4,5,6,7,8]
         Speed=[60,62,61,58,56,57,46,63]​​​​​
"""

import numpy as np
Days=np.array([1,2,3,4,5,6,7,8]) 
Speed=np.array([60,62,61,58,56,57,46,63])
plt.plot(Days,Speed)
plt.show()



"""Plot Axes Labels, Chart title, Legend, Grid in Car minimum, Maximum and average
speed in 8 days.
days=[1,2,3,4,5,6,7,8]
max_speed=[80,91,92,88,77,79,76,75]
min_speed=[42,43,40,42,33,36,34,35]
avg_speed=[46,58,57,56,40,42,41,36]
"""

days=[1,2,3,4,5,6,7,8]
max_speed=[80,91,92,88,77,79,76,75] 
min_speed=[42,43,40,42,33,36,34,35] 
avg_speed=[46,58,57,56,40,42,41,36]
plt.plot(days,max_speed,days,min_speed,days,avg_speed)
plt.show()

"""Plotting a basic sine graph by adding more features. Adding Multiple plots by
Superimposition like cosine wave.
"""

time= np.arange(0, 10, 0.1)
amplitude   = np.sin(time)
amp_1=np.cos(time)
plt.plot(time, amplitude,time,amp_1)

"""Plot Simple bar chart showing popularity of Programming Languages.
Languages =[&#39;Python&#39;, &#39;SQL&#39;, &#39;Java&#39;, &#39;C++&#39;, &#39;JavaScript&#39;]
Popularity = [56, 39, 34, 34, 29]
Security = [44 ,36 ,55, 50, 42]
Plot Multiple Bars showing Popularity and Security of major Programming
Languages. Also Create Horizontal bar chart using barh function.
"""

Lang=['Python', 'SQL', 'Java', 'C++', 'JavaScript']
Popularity = [56, 39, 34, 34, 29]
Security = [44 ,36 ,55, 50, 42]
plt.bar(Lang,Popularity)
plt.show()

plt.barh(Lang,Security,color="red")
plt.show()

plt.bar(Lang,Security,color="red")
plt.show()

plt.barh(Lang,Popularity)
plt.show()

"""Plot Histogram, We have a sample data of Students marks of various Students, we will
try to plot number of Students by marks range and try to figure out how many Students
are average, below-average and Excellent.
Marks = [ 61,86,42,46,73,95,65,78,53,92,55,69,70,49,72,86,64]
Histogram showing Below Average, Average and Execellent distribution
40-60: Below Average
60-80: Average
80-100: Excellent
"""

Marks = [ 61,86,42,46,73,95,65,78,53,92,55,69,70,49,72,86,64]
plt.hist(Marks)
plt.show()

"""Titanic Data Set Download Data
 Load the data file
 (i) Create a pie chart presenting the male/female proportion 
 (ii) Create a scatterplot with the Fare paid and the Age, differ the plot color by
Gender.
"""

from google.colab import files
files.upload()

data1=pd.read_csv("train.csv")
data1

data1["Sex"]

a=data1.loc[data1["Sex"] == "male"]
a
print(len(a))
b=data1.loc[data1["Sex"] == "female"]
print(len(b))

import numpy as np
y = np.array([577,314])
plt.pie(y)
plt.show()

plt.scatter(data1["Fare"],data1["Age"])
plt.show()

