# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZXZQw37elLxyAjJhA5UsRrf8o0XJGGbT
"""

import pandas as pd
pd.__version__

from google.colab import files
files.upload()

import pandas as pd
data=pd.read_csv("train.csv")
print(data)

data.head(10)

data.tail()

data.info()

data.describe().T

data.describe()

male=data[data.Sex=="male"].count()
male

data.groupby()

male=data.Sex[data.Sex=="male"].count()
female=data.Sex[data.Sex=="female"].count()
male+female

import numpy as np
my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]])
my_column_names = ['temperature', 'activity']
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)
print(my_dataframe)

my_dataframe["adjusted"]=my_dataframe["activity"]+4
print(my_dataframe)

